%dw 2.0
output application/java
---
payload map {
    //Item Info
    "Name": $.IMA_ItemName,
    "ItemID__c": $.IMA_ItemID,
    "SupercededItemID__c": $.IMA_SupercededItemID,
    "ItemName__c": $.IMA_ItemName,
    "Description": $.IMS_LongDesc,
    "Product_Category__c": $.IMA_Classification, 
    "UnitMeasure__c": $.IMA_UnitMeasure,
    "Price__c": $.IMA_Price,
    "PriceMatrixFlag__c": $.IMA_PriceMatrixFlag,
    "PriceCodeID__c": $.IMA_PriceCodeID,
    "SalesTaxFlag__c": $.IMA_SalesTaxFlag,
    "Item_Type_Code__c": $.IMA_ItemTypeCode,
    "Customer_Product_ID__c": $.IMA_CustItemID,
    "Rev_Level__c": $.IMA_RevLevel,
    "OnHandQty__c": $.IMA_OnHandQty,
    "Family": $.IMA_ProdFam, 
    "ModelName": $.IMA_ProdModel, 
    "LeadTimeCode__c": $.IMA_LeadTimeCode,
    "PurLeadTime__c": $.IMA_PurLeadTime,
    "MfgLeadTime__c": $.IMA_MfgLeadTime,
    "ItemStatusCode__c": $.IMA_ItemStatusCode,
    "SalesConvFactor__c": $.IMA_SalesConvFactor,
    "RoutHrsExcptFlag__c": $.IMA_RoutHrsExcptFlag,
    "GLSalesAcctNbr__c": $.IMA_GLSalesAcctNbr,
    "ERP_Customer_ID__c": $.IMA_CustomerID,
    "OutplantLeadTime__c": $.IMA_OutplantLeadTime,
    "LastModifiedDate__c": $.IMA_LastModifiedDate as DateTime,
    "Min_Sales_Quantity__c": $.IMA_MinSalesQuantity,
    "SBQQ__NonDiscountable__c": $.IMA_NonDiscountable,
    "Non_Commissionable__c": $.IMA_NonCommisionable,
    "Length__c": $.IMA_Length,
    "Length_Unit_of_Measure__c": $.IMA_LengthUnitMeasure,
    "Width__c": $.IMA_Width,
    "Width_Unit_of_Measure__c": $.IMA_WidthUnitMeasure,
    "Height_Length__c": $.IMA_Height,
    "Height_Length_Unit_of_Measure__c": $.IMA_HeightUnitMeasure,
    "Weight_Unit_of_Measure__c": $.IMA_WeightUnitMeasure,
    //Attributes
    "Decor__c": $.Attribute1_Value,
    // "": $.Attribute2_Value,
    // "": $.Attribute3_Value,
    "D_cor_1_Direction__c": $.Attribute4_Value,
    "Resin_Type__c": $.Attribute5_Value,
    "Gauge__c": $.Attribute6_Value,
    "Width__c": $.Attribute7_Value,
    "Height_Length__c": $.Attribute8_Value,
    "Front_Finish__c": $.Attribute9_Value,
    "Back_Finish__c": $.Attribute10_Value,
    "Front_Add_on_1__c": $.Attribute11_Value,
    "Front_Add_on_2__c": $.Attribute12_Value,
    "Front_Add_on_3__c": $.Attribute13_Value,
    "Back_Add_on_1__c": $.Attribute14_Value,
    "Back_Add_on_2__c": $.Attribute15_Value,
    "Back_Add_on_3__c": $.Attribute16_Value,
    // "": $.Attribute17_Value,
    "Kuvio_Tiles_Finish__c": $.Attribute18_Value,
    "Solution_Number__c": $.Attribute19_Value,
    // "": $.Attribute20_Value,
    // "": $.Attribute21_Value,
    // "": $.Attribute22_Value,
    // "": $.Attribute23_Value,
    // "": $.Attribute24_Value,
    // "": $.Attribute25_Value,
    // "": $.Attribute26_Value,
    // "": $.Attribute27_Value,
    "Edge_Finish__c": $.Attribute28_Value,
    "Edge_Profile__c": $.Attribute29_Value,
    "Price_Basis__c": $.Attribute30_Value
}