api:
  id: "19599698"

sfdc: 
  sapi:
    protocol: "HTTPS"
    host: "gravityforms-sfdc-sys-api-prod-wpbs9l.internal-07nv9h.usa-e2.cloudhub.io"
    port: ""
    basepath: "/api"
    generateQuote:
      method: "POST"
      path: "/generate-quote"

#gravityforms-sfdc-sys-api-prod-wpbs9l.internal-07nv9h.usa-e2.cloudhub.io
#gravityforms-sfdc-sys-api-prod-wpbs9l.07nv9h.usa-e2.cloudhub.io