#This is the api instance id for prod environment
api:
  id: ""

# salesforce username for prod environment 
salesforceComposite:
  username: "konark.saini@caeliusconsulting.com.lumicor.prod"
  link: "https://login.salesforce.com/services/oauth2/token"

#These are now the prod configurations