salesforceComposite:
  client_id: "![YLdJq1lAZRNxFgMB86Y6MVyEY0lv4vYGVDNXubkOGREQ4J/Xo2+0FimOVx6bnopmz8ON9H7UZHuOwqrPjiSvQ/KN1gzCeHbDB4jgjgeToUsr2mA1oohOpg==]"
  client_secret: "![6rbuoBwN4abKkKmINmYb0Y4nhIrM2wpfNGHKMjaNKprdSphQJCIrrc4VEBZq8iVhMnxvPEqbuPF9lu0gdt8l0+7Bpr8kgUPR]"
  password: "![UBjxBR5W5CVQCecQkuF4bw==]"
  securityToken: "![eb4yHD70k36sWNnOK37sh9ECf6KvnA44eN75yCKlZx0=]"