salesforceComposite:
  client_id: "![FEyzOZInMh6WUYIK6tTeD1n1YzZgb7t69vxlYSYncopuN1yWnlapPkrYtyUOlEdhJiSgOGVsTp0aBwE+Yexgmm356g226wTmogcFcqHqtiNTLUziCA7mFw==]"
  client_secret: "![MTvB+dtzBOdZ+o9ehp6Rxp41gnzeOqsl4ocv0t7vyAPSNSikrRJeACl1maADhMbm+JWCGzFqvv8NEJrd2o1FgQlSAlnG9dki]"
  password: "![E6WY97pM7LKoQxpsrnjh7Q==]"
  securityToken: "![2wvOPYiOSEVlZM3S4tTE+rpCVe5WiLU+aA1Zl4lrADY=]"
  
#These are now prod configurations