salesforceComposite:
  client_id: "![YLdJq1lAZRNxFgMB86Y6MVyEY0lv4vYGVDNXubkOGREQ4J/Xo2+0FimOVx6bnopmz8ON9H7UZHuOwqrPjiSvQ/KN1gzCeHbDB4jgjgeToUsr2mA1oohOpg==]"
  client_secret: "![6rbuoBwN4abKkKmINmYb0Y4nhIrM2wpfNGHKMjaNKprdSphQJCIrrc4VEBZq8iVhMnxvPEqbuPF9lu0gdt8l0+7Bpr8kgUPR]"
  password: "![gMXm9RAZD4Ij+qR8HOt5tA==]"
  securityToken: "![iUWd6ZGdR3MHmwtGzvIrecj8JQ/z87vNBan5+L5fueU=]"