api:
  id: "19820491"

Database:
  Host: "10.0.10.45"
  Port: "1433"
  User: "MuleSoftIntegration"
  
Salesforce:
  userName: "konark.saini@caeliusconsulting.com.lumicor.prod"
  TokenEndpoint: "https://login.salesforce.com/services/oauth2/token"